name: CI - Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install .
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=p2pchat --cov-report=xml

    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
